language: node_js
node_js:
- node
cache:
  yarn: true
notifications:
  email:
    on_failure: always
    on_success: never
before_install:
- yarn config set progress=false
before_script:
- export NODE_ENV=production
script: yarn build
before_deploy:
  - .travis/setup-git.sh > /dev/null 2>&1
deploy:
  - provider: script
    script: yarn semantic-release
    skip_cleanup: true
    on:
      branch: master
