language: node_js
node_js:
- node
cache:
  directories:
  - "${HOME}/.cache/yarn"
  - node_modules
notifications:
  email:
    on_failure: always
    on_success: never
before_install:
- yarn config set progress=false
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
before_deploy:
- git config --local user.name "Travis CI"
- git config --local user.email "travis@travis-ci.org"
- tar -czvf Site_Build.tar.gz dist firebase.json
deploy:
  - provider: releases
    file:
    - Site_Build.tar.gz
    api_key:
      secure: FCm/333/ohaqSQk7aBfqsJLP0eIgYzYQHft6i3cJaL6WCqihcuunwAS72X164b0z/L0sJ4GFPboGmZ2Lud/bmR3MLtg633zKrukwqlg5B1OoHM/oOLSJF2U7a1k8vefe4mWBb2MY/8aH2NiOokZtspIZoMH19eLMgiCJ8tExzqSsWVdDGbpckhYRgv7tCK55Zp1Z847tHAR8cbzvQVuWWv3Cy2foWjy5FHADLwJNY6X54TaHZka4LMc0kYevnupbngOnfY0u05xDEn+vWgppex30SLZXipUdcS56gegvvgexONvQv5I6E+Td4QZdOF59iCp1FRqt3wvxdoJznv+zFG1KcrIVBa5ffanAQu54PRUAJrc5kLNaxwnEKUe2SKFOCRfRDpn8xXSdEu3z1v7NIJK8frFLA2SFCp++SWN1BJC+R2QhNz2rd8ENoJCl/TtmaSuEk8uN6CLs37MjpEhosER+5+Lroy2ZCRnCdcHtTagkKuNVSJSlzD++quqQIZy+oTro6IZi46HXe3+qWvq/ZOVnkGfC8OtlowvKrQq4xkdPyL95thXrWHlQ/NlLCZ5YJgYCmUMkxW8a3X3asrQkvyuS2MWUgz9NMOcMWeeWtj2kg0l4L4eFwbC34/FePDp2y0o8y32j39mI0rZ849FdZXS2yLE7GwuuMt49ditiIJ8=
    skip_cleanup: true
    on:
      tags: true
      repo: genpw/genpw.com
  - provider: firebase
    token:
      secure: VuEc07somgxhxsYh9xNM1CFWnUKva1T00yi7YYuf7CeSJxrjyPk7Qm8/uiMk1eHVGkJdhAjV3XV8pNJEWnKKsSkVVDHVLaWurg9L2BiMwh8V4Xjub+EcKTg3tGV/We4mKOLkvjFtqE+RTJ/gH5+fjB3SedSuQmhkjW1W3ktpoiSZxJfmyKMLn58PLnEG8izVT+6ClhRw3fc/qIjRJabcPI0QBEDhp+tN7pPoyDaz+EnCvbPIlXViZdZVMyXzEamtXa6pyO46GiRRUWw5KaZDR4ISvAZKNCw+eDC1DqX2i3aeljUhMAvRV1zrHHC6H4LjdshxcYIE+3cLlKlYlgNzJ+nO+HYCDHruSA2HBKGJrnpH9U/XGWTh3HFXt27bvD5W2eh8b0VxMZhpQis4JcqgZg7kXgM0zJhSrmgG2bUkplacz6j49zbhQVCX/4mcCEfkeggOJflNsUDCctTXIpZCoK3K6wzbk9qOYw4daPMRpxGw9OrpkIF0ivNQQEfHx2JyJCJ1N5ziFL26vy2ZcMb2HMOf1f63z6QlHJzaU8GnzB0hhMSEGcuVVWfGuLehIxNvWCYAqEzGNXPAVWRcuKVY1KXWzxIedlC/4OkSPHGETW4/mHMmrLN5Q8wzF29tDvfMNRlq1/DxPV00yCVfKFeYxyBw3h4gtWbDI0qiWRBP2RA=
    message: 'A Message'
