language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - "${HOME}/.cache/yarn"
  - node_modules
notifications:
  email:
    on_failure: always
    on_success: never
before_install:
- yarn config set progress=false
- yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- export NODE_ENV=production
script: yarn build
after_script: greenkeeper-lockfile-upload
before_deploy:
  - .travis/setup-git.sh > /dev/null 2>&1
deploy:
  - provider: script
    script: yarn semantic-release
    skip_cleanup: true
    on:
      branch: master
