defaults: &defaults
  working_directory: ~/project/repo
  docker:
    - image: circleci/node:latest@sha256:13d8525efd6ca829e4a49265fb9a84d2053750ef40b6a5a6d3b6f5f6c2db542e

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - v1-dependencies-{{ .Branch }}-
          - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build Site
          command: yarn build
          environment:
            NODE_ENV: production
      - persist_to_workspace:
          root: ~/project
          paths:
            - repo
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: .circleci/setup-git.sh > /dev/null 2>&1
      - run: yarn semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          context: Release
          requires:
            - test
